Develop
vick25/gestionnaire_taches pull request #1
Opened 2024-11-26 21:55 UTC by vick25

2024-11-27 13:25 UTC, Sacre-MBIKU-WAKANE requested changes

2024-11-27 13:25 UTC, Sacre-MBIKU-WAKANE commented on main.js
Tu dois trouver le moyen d'avoir une fonction, qui permet de save la tâche directement après la création comme tu as fait pour la modification et la suppression

2024-11-27 13:25 UTC, Sacre-MBIKU-WAKANE commented on main.js
> +const trierTachesParPriorites = (priorite) => {
Tu es sensé comparer les niveaux de priorités pour mettre les tâches en ordre croissant ou décroissant

2024-11-27 15:45 UTC, vick25 commented on main.js
> +const trierTachesParPriorites = (priorite) => {
Done!

2024-11-27 15:47 UTC, vick25 commented on main.js
Done!

2024-12-03 20:13 UTC, Sacre-MBIKU-WAKANE approved these changes

2024-12-04 08:17 UTC, merged